name: ekskool_v1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^5.1.0
  feather_icons: ^1.2.0
  flutter_toggle_tab: ^1.4.1
  convex_bottom_bar: ^3.2.0
  icons_plus: ^4.0.0
  circle_nav_bar: ^2.0.1+1
  firebase_core: 2.15.1
  firebase_auth: 4.9.0
  cloud_firestore: 4.9.1
  shared_preferences: 2.2.1
  flutter_native_splash: 2.3.3
  dropdown_search: ^5.0.6
  intl: 0.18.1
  rxdart: 0.27.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

